name: Update schema

on:
  schedule:
    # Every day at 9:41
    - cron: '41 9 * * *'
  workflow_dispatch:

permissions:
  # So this action may push changes back to the repo
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update the Sketch Cloud GraphQL schema if needed
        run: |
          npx get-graphql-schema https://graphql.sketch.cloud/api > new-schema.graphql
          if [ ! -s new-schema.graphql ]; then
            echo "🚫 Failed to download the latest GraphQL schema"
            exit 1
          fi

          node normalize-schema.js new-schema.graphql
          mv -f new-schema.graphql schema.graphql

          if [[ $(git status --porcelain --untracked-files=no schema.graphql) ]]; then
            git config user.name "Dmitry Rodionov"
            git config user.email i.am.rodionovd@gmail.com
            git add schema.graphql
            git commit -m "♻️ $(date "+%d.%m.%Y")"
            git push
            echo "✅ Updated schema.graphql"
          else
            echo "👋 No updates found. Will check again tomorrow"
          fi
